services:
  - type: web
    name: taskmate-backend
    env: node
    region: oregon
    plan: free
    branch: master
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false

